"""
Smriti 2.0 — Project-level memory layer.

Two-layer design:
  Layer 1 (always): llmwiki-style Markdown pages in project-memory/{user_id}/
  Layer 2 (optional): Graphiti temporal knowledge graph — activates when
    GRAPHITI_NEO4J_URI + GRAPHITI_NEO4J_USER + GRAPHITI_NEO4J_PASSWORD are set.

Usage:
    from smriti_v2 import add_episode, get_project_context, WIKI_DIR
    await add_episode(user_id, session_id, avatar, task, result)
    context = await get_project_context(user_id, query)
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# ── Storage ────────────────────────────────────────────────────────────────────

import sys as _sys_nc
_sys_nc.path.insert(0, str(Path(__file__).parent.parent))
from narad_config import WIKI_DIR

# ── Entity type → wiki page mapping ───────────────────────────────────────────

ENTITY_TYPES = {
    "decision":  "decisions",     # architectural/product decisions
    "feature":   "features",      # code features being built
    "goal":      "goals",         # user goals across sessions
    "insight":   "insights",      # avatar discoveries/observations
    "context":   "context",       # general project context
}

# ── Graphiti (optional) ────────────────────────────────────────────────────────

_graphiti_client: Any = None
_graphiti_enabled = False


def _init_graphiti() -> None:
    global _graphiti_client, _graphiti_enabled
    if _graphiti_enabled:
        return
    uri  = os.environ.get("GRAPHITI_NEO4J_URI")
    user = os.environ.get("GRAPHITI_NEO4J_USER", "neo4j")
    pwd  = os.environ.get("GRAPHITI_NEO4J_PASSWORD")
    if not uri or not pwd:
        return
    try:
        from graphiti_core import Graphiti
        _graphiti_client = Graphiti(uri, user, pwd)
        _graphiti_enabled = True
    except Exception:
        pass  # Graphiti unavailable — wiki layer still works


# ── Markdown wiki helpers ──────────────────────────────────────────────────────

def _user_wiki_dir(user_id: str, project_id: str = "general") -> Path:
    user_root = WIKI_DIR / user_id
    # One-time migration: flat *.md files → general/ subdir
    if user_root.exists():
        flat_md = [f for f in user_root.glob("*.md")]
        if flat_md:
            general_dir = user_root / "general"
            general_dir.mkdir(parents=True, exist_ok=True)
            for f in flat_md:
                dest = general_dir / f.name
                if not dest.exists():
                    f.rename(dest)
                else:
                    f.unlink()  # already migrated, remove duplicate
    d = WIKI_DIR / user_id / project_id
    d.mkdir(parents=True, exist_ok=True)
    return d


def _entity_path(user_id: str, entity_type: str, project_id: str = "general") -> Path:
    filename = ENTITY_TYPES.get(entity_type, entity_type) + ".md"
    return _user_wiki_dir(user_id, project_id) / filename


def _append_to_wiki(user_id: str, entity_type: str, entry: str, project_id: str = "general") -> None:
    """Append a timestamped entry to the appropriate wiki page."""
    path = _entity_path(user_id, entity_type, project_id)
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    header = f"## {ts}\n"
    if not path.exists():
        title = ENTITY_TYPES.get(entity_type, entity_type).upper()
        path.write_text(f"# {title}\n\n_{user_id} project memory — auto-generated by Scribe_\n\n")
    with open(path, "a") as f:
        f.write(f"\n{header}{entry.strip()}\n")


def get_wiki_pages(user_id: str, project_id: str = "general") -> list[dict[str, str]]:
    """Return all wiki pages for a project as {entity, filename, preview}."""
    d = _user_wiki_dir(user_id, project_id)
    pages = []
    for p in sorted(d.glob("*.md")):
        text = p.read_text()
        first_line = next((l for l in text.splitlines() if l.strip() and not l.startswith("#")), "")
        pages.append({
            "entity":     p.stem,
            "filename":   p.name,
            "preview":    first_line[:120],
            "size_chars": len(text),
        })
    return pages


def get_wiki_page(user_id: str, entity: str, project_id: str = "general") -> str | None:
    """Return the full content of a wiki page, or None if not found."""
    path = _entity_path(user_id, entity, project_id)
    return path.read_text() if path.exists() else None


def put_wiki_page(user_id: str, entity: str, content: str, project_id: str = "general") -> None:
    """Write (overwrite) a wiki page with user-provided content."""
    path = _entity_path(user_id, entity, project_id)
    path.write_text(content)


# ── Episode ingestion ──────────────────────────────────────────────────────────

def _classify_episode(avatar: str, task: str, result: str) -> str:
    """Classify an episode to an entity type using simple heuristics."""
    text = (task + " " + result).lower()
    if any(kw in text for kw in ["decide", "decision", "chose", "going with", "architecture", "approach"]):
        return "decision"
    if any(kw in text for kw in ["implement", "build", "write code", "create function", "add feature"]):
        return "feature"
    if any(kw in text for kw in ["goal", "objective", "aim", "want to", "planning to", "target"]):
        return "goal"
    return "insight"  # default: general observation


def _format_wiki_entry(avatar: str, task: str, result: str) -> str:
    """Format one episode as a Markdown wiki entry."""
    task_short = task[:300] + ("…" if len(task) > 300 else "")
    parts = [f"**Avatar:** {avatar}  \n", f"**Task:** {task_short}  \n"]
    if result.strip():
        result_short = result[:500] + ("…" if len(result) > 500 else "")
        parts.append(f"**Summary:** {result_short}\n")
    return "".join(parts)


async def add_episode(
    user_id: str,
    session_id: str,
    avatar: str,
    task: str,
    result: str,
    project_id: str = "general",
) -> None:
    """Record one avatar interaction as a project memory episode."""
    if not task.strip():
        return  # nothing to record without a task

    entity_type = _classify_episode(avatar, task, result)
    entry = _format_wiki_entry(avatar, task, result)
    _append_to_wiki(user_id, entity_type, entry, project_id)

    # Graphiti (optional layer)
    _init_graphiti()
    if _graphiti_enabled and _graphiti_client is not None:
        try:
            await _graphiti_client.add_episode(
                name=f"{avatar}-{session_id[:8]}",
                episode_body=f"Task: {task}\n\nResult: {result}",
                source_description=f"Avatar: {avatar}",
                reference_time=datetime.now(timezone.utc),
                group_id=user_id,
            )
        except Exception:
            pass  # Graphiti failure never breaks the main flow


async def get_project_context(
    user_id: str, query: str, top_n: int = 5, project_id: str = "general"
) -> str:
    """
    Retrieve relevant project context for a query.

    Tries Graphiti first (hybrid semantic + graph traversal);
    falls back to keyword scan of wiki Markdown pages for the given project.
    """
    # Graphiti path
    _init_graphiti()
    if _graphiti_enabled and _graphiti_client is not None:
        try:
            results = await _graphiti_client.search(query, group_ids=[user_id], num_results=top_n)
            if results:
                lines = [f"- {r.fact}" for r in results]
                return "[PROJECT MEMORY — from Graphiti]\n" + "\n".join(lines)
        except Exception:
            pass

    # Fallback: keyword scan of project wiki pages
    d = _user_wiki_dir(user_id, project_id)
    hits: list[tuple[int, str, str]] = []
    query_words = set(re.findall(r"\w+", query.lower()))

    for p in sorted(d.glob("*.md"), reverse=True):
        text = p.read_text()
        words = set(re.findall(r"\w+", text.lower()))
        overlap = len(query_words & words)
        if overlap > 0:
            hits.append((overlap, p.stem, text))

    hits.sort(key=lambda x: -x[0])
    if not hits:
        return ""

    snippets = []
    for _, entity, text in hits[:top_n]:
        snippet = text[-400:].strip()
        snippets.append(f"[{entity.upper()}]\n{snippet}")

    return "[PROJECT MEMORY — from wiki]\n\n" + "\n\n---\n\n".join(snippets)
